# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYhdsWSrkRpodeJhWxYB5-21_E69rsc1
"""

#TO CREATE AN ARRAY(numpy-numerical python)
import numpy as np
arr=np.array([1,2,3])
print(arr)

a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

#ONCE
np.ones((2,3))

#ZEROS
np.zeros((2,3))

#LINSPACE
np.linspace(0,1,5)

#RANGE(strating value,ending value,updation)
np.arange(1,10,2)

#ARRAY DIMENSIONS
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr.shape----#used to find the shape like rows and columns

#used to find the shape like rows and columns
arr.shape----

#to find the nbr of dimensions
arr.ndim

arr1=np.array([10,20,30])
print(arr1)
arr1.shape

coll=(5,10,15)
arr=np.array(coll)
print(arr)

"""data type:
i indicates---integer,
b-boolean,
u-unsigned integer,
f-floot,
c-complex floot,
m-time delta,
M-datetime,
O-object,
S-string,
U-unique code string,
v-fixed chunck of memory for other type(void),
for i u f S U we can define size as well
"""

arr=np.array([1,2,3],dtype=float)
print(arr)
print(arr.dtype)

arr=np.array([1,2,3],dtype=str)
print(arr)
print(arr.dtype)

arr=np.array([1,2,3],dtype=bool)
print(arr)
print(arr.dtype)

arr=np.array([1,2,3],dtype=complex)
print(arr)
print(arr.dtype)

arr=np.array([10,20,30,40])
print(arr.shape)

"""here the shape always return tuple
1D-(n,)
2D-(rows,cols)
3D-(block,rows,cols)

"""

arr=np.linspace(0,1,5)
print(arr)

arr=np.arange(0,1,0.2)
print(arr)

arr=np.random.randint(1,10,5)
print(arr)

arr=np.random.randint(1,10,(2,2,3))
print(arr)

#RESHAPE
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
print(b)

a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(-1)
print(b)

a=np.zeros(10)
print(a)

a=np.zeros((2,3))
print(a)

a=np.zeros((5,2,3))
print(a)

a=np.identity(3)
print(a)

#INDEXING
a=np.array([1,2,3,4])
a[2]

s=np.array([True,12,5])
d=s.copy()
s[1]=120
print(s)

s=np.array([True,12,5])
d=s.copy()
s[1]=120
print(d)

a=np.array([1,2,3,4],)
b=a.view()
print(id(a))
print(id(b))
a[1]=200
print(a)
print(b)

#2D
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.view()
print(id(a))
print(id(b))
a[0,1]=200
print(a)
print(b)

#3D
a=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
b=a.view()
print(id(a))
print(id(b))
a[1]=200
print(a)
print(b)

#ARRAY WITH ARRAY(RELATIONAL)
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

#BITWISE OPERATOR
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a&b)
print(a/b)
print(~b)
print(a^b)

#RELATIONAL OPERATOR
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)

#ARRAY WITH CONSTANT
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a//2)
print(a%2)
print(a**2)

#ARRAY WITH BUILT IN FUNCTIONS
a=np.array([1,2,3])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.prod(a))

np.arange(0,10)

